apiVersion: v1
kind: Service
metadata:
  name: fileserver-service-external
spec:
  selector:
    app: file-server
    type: file-server-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30013
  type: NodePort
  