apiVersion: v1
kind: Service
metadata:
  name: fileserver
spec:
  selector:
    app: file-server
    type: file-server-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  