apiVersion: v1
kind: Service
metadata:
  name: messenger-service-external
spec:
  selector:
    app: messenger
    type: messenger-pod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30012
  type: NodePort
  