apiVersion: v1
kind: Pod
metadata:
  name: messenger-pod
  labels:
    app: messenger
    type: messenger-pod
spec:
  containers:
    - name: messenger-pod
      image: msaeed1381/messenger:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: messenger-pod
          containerPort: 8000
          protocol: TCP
  restartPolicy: Always
  